options:
  suite: 'suite name'
  build: '1' #
  backtrace: false
  git_commit:
  git_branch:
dbconnection:
  adapter: postgresql
  database:  rspec
  username: postgres
  password: test123!
  host: localhost
  port: 5432
