options:
  suite: "full regression" #this can be used in a setup where multiple projects share the same test results database
  build: "12345" #
  backtrace: false #set backtrace to true for more details and metadata
dbconnection:
  adapter: postgresql
  database:  rspec
  username: postgres
  password: test123!
  host: localhost
  port: 5432
